name: Read PR
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  update-release-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Scan and remove stale deployments 📖
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: |
          node ./script/clean_deploys.js


