name: Release PR
on:
  pull_request:
    types:
      - opened
    branches:
      - v1

jobs:
  create-release:
    if: contains(github.head_ref, 'release/v') && ${{ github.event.action === 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/github-script@v5
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        with:
          script: |
            const { BRANCH_NAME } = process.env;
            const { owner, repo } = context.repo;
            const tag_name = BRANCH_NAME.replace('release/v', '')

            console.log(repo)
            console.log(github.event.pull_request)

#            const milestone = github.rest.issues.getMilestone({
#              owner,
#              repo,
#              milestone_number: tag_name,
#            });

#            const release = github.rest.repos.createRelease({
#              owner,
#              repo,
#              tag_name: ,
#            });


