name: Patch hotfix to production
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  patch-hotfix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - id: fetch_latest_release
        run: |
          latest_release=$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Nanxy-Tran/random_reviewer/releases/latest
          )
          version=${{ fromJson(latest_release).tag_name }}
          echo "::set-output name=latest_release::${version}"

      - name: Patch hotfix to production 🔥
        env:
          LATEST_VERSION: ${{ steps.fetch_latest_release.outputs.latest_release }}
        run: |
          echo ${LATEST_VERSION:1}


